language: php

services:
- docker

script:
- docker run -v $PWD:/app phpqa/php-cs-fixer fix . --dry-run

notifications:
  slack:
    rooms:
    - ipssi-d19-1:3U0tNTwfovSqXR04sBm4G5HQ#memo-riz
    on_success: change
    on_failure: always
